/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Desktop;
import java.net.URL;

/**
 *
 * @author Nima's Stuff
 */
public class Exit extends javax.swing.JFrame {

    /**
     * Creates new form Exit
     */
    public Exit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        X = new javax.swing.JButton();
        GitD = new javax.swing.JButton();
        GitN = new javax.swing.JButton();
        LnD = new javax.swing.JButton();
        LnN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        X.setBackground(new java.awt.Color(255, 0, 102));
        X.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        X.setForeground(new java.awt.Color(255, 255, 255));
        X.setText("X");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });
        getContentPane().add(X);
        X.setBounds(550, 0, 100, 40);

        GitD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/GithubBtn.png"))); // NOI18N
        GitD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GitDActionPerformed(evt);
            }
        });
        getContentPane().add(GitD);
        GitD.setBounds(20, 270, 100, 90);

        GitN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/GithubBtn.png"))); // NOI18N
        GitN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GitNActionPerformed(evt);
            }
        });
        getContentPane().add(GitN);
        GitN.setBounds(520, 270, 100, 90);

        LnD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Libtn.png"))); // NOI18N
        LnD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnDActionPerformed(evt);
            }
        });
        getContentPane().add(LnD);
        LnD.setBounds(20, 170, 100, 90);

        LnN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Libtn.png"))); // NOI18N
        LnN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnNActionPerformed(evt);
            }
        });
        getContentPane().add(LnN);
        LnN.setBounds(520, 170, 100, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nima's Stuff\\Desktop\\frames\\NewExit.jpeg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_XActionPerformed
 public static void openWebpage(String urlString) {
    try {
        Desktop.getDesktop().browse(new URL(urlString).toURI());
    } catch (Exception e) {
        e.printStackTrace();
    }
 }
    private void LnNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnNActionPerformed
               openWebpage("https://www.linkedin.com/in/nima-kamali/");

        // TODO add your handling code here:
    }//GEN-LAST:event_LnNActionPerformed

    private void GitNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GitNActionPerformed
        openWebpage("https://github.com/NimakamaliLassem");

        // TODO add your handling code here:
    }//GEN-LAST:event_GitNActionPerformed

    private void LnDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnDActionPerformed
                   openWebpage("https://www.linkedin.com/in/davut-atajanov/");

        // TODO add your handling code here:
    }//GEN-LAST:event_LnDActionPerformed

    private void GitDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GitDActionPerformed
                       openWebpage("https://github.com/davut-atajanov");

            // TODO add your handling code here:
    }//GEN-LAST:event_GitDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GitD;
    private javax.swing.JButton GitN;
    private javax.swing.JButton LnD;
    private javax.swing.JButton LnN;
    private javax.swing.JButton X;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
