/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static java.awt.image.ImageObserver.HEIGHT;
import java.io.Serializable;

/**
 *
 * @author Nima's Stuff
 */
public class HospitalFrame extends javax.swing.JFrame{

    ClientFrame cf2;
     public boolean closed =false;
     public boolean spacheck=false;
     public static String docName;
     public static int stat;
     
    
    /**
     * Creates new form HospitalFrame
     */
    public HospitalFrame(ClientFrame cf3) {
        initComponents();
        cf2=cf3;
       
    }

 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hospital = new javax.swing.JPanel();
        docc = new javax.swing.JComboBox<>();
        statc = new javax.swing.JComboBox<>();
        close = new javax.swing.JButton();
        conf = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Hospital.setLayout(null);

        docc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr.EliBerg", "Dr.FelixCzerwinski", "Dr.HaroldHrobsky", "Dr.AntoinetteImbimbo", "Dr.ConstanceKerson", "Dr.GiaMcginister" }));
        docc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doccActionPerformed(evt);
            }
        });
        Hospital.add(docc);
        docc.setBounds(160, 200, 190, 20);

        statc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "4", "3", "2", "1" }));
        Hospital.add(statc);
        statc.setBounds(160, 240, 190, 20);

        close.setBackground(new java.awt.Color(255, 0, 51));
        close.setText("X");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        Hospital.add(close);
        close.setBounds(410, 0, 50, 30);

        conf.setText("CONFIRM");
        conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confActionPerformed(evt);
            }
        });
        Hospital.add(conf);
        conf.setBounds(360, 200, 90, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Hospital-FIXED.png"))); // NOI18N
        Hospital.add(jLabel2);
        jLabel2.setBounds(0, 0, 460, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Hospital, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Hospital, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.setVisible(false);
        closed=true;
        cf2.setVisible(true);
        cf2.uncheck(closed);
        cf2.unchecks(spacheck);
        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void confActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confActionPerformed

        docName = String.valueOf(docc.getSelectedItem());
        stat = Integer.parseInt(String.valueOf(statc.getSelectedItem()));
        //        System.out.println(stat);
       if(cf2.getSpac1().isSelected()){
        if(stat<4) 
       {
            javax.swing.JOptionPane.showMessageDialog(Hospital,
                    "YOUR HEALTH CONDITION IS NOT SUITABLE FOR SPA AND SUANA"
                                , "PASSWORD ERROR", HEIGHT);
           spacheck=true;
       }
                cf2.unchecks(spacheck);
        if(!cf2.getRehabc().isSelected())
            closed=true;
        else closed=false;
       }
           
        this.setVisible(false);
        cf2.setVisible(true);
        cf2.uncheck(closed);
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_confActionPerformed

    private void doccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_doccActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Hospital;
    private javax.swing.JButton close;
    private javax.swing.JButton conf;
    private javax.swing.JComboBox<String> docc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> statc;
    // End of variables declaration//GEN-END:variables
}
