package GUI;


import java.awt.Desktop;
import java.io.Serializable;
import java.net.URL;
import static java.util.Objects.isNull;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import static jdk.nashorn.internal.runtime.regexp.joni.Syntax.Java;
import system.UniverseHealthSys;
import static system.UniverseHealthSys.searchPerson;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nima's Stuff
 */
public class LoginFrame extends javax.swing.JFrame {
      private String Uname;
      private String passn;
      private int UID;
      ClientFrame cf = new ClientFrame(this);
      CoachFrame cof = new CoachFrame(this);
      PostRFrame pf;
      String finalId="";
    /**
     * Creates new form NewJFrame
     */
    public LoginFrame(PostRFrame pf2) {
        initComponents();
        
      pf=pf2;
        
    }

//    public JLabel getjLabel1() {
//        return jLabel1;
//    }
//
//    public JButton getFakex() {
//        return fakex;
//    }
//
//    public JTextField getId() {
//        return Id;
//    }
//
//    public JTextField getPass() {
//        return pass;
//    }
//
//     public void goToLogIn()
//    {
//        jPanel3.setVisible(false);
//        jPanel1.setVisible(true);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        npass = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        next2 = new javax.swing.JButton();
        fakex2 = new javax.swing.JButton();
        eulacb = new javax.swing.JCheckBox();
        eula = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nsname = new javax.swing.JTextField();
        preId = new javax.swing.JTextField();
        backlog = new javax.swing.JButton();
        next1 = new javax.swing.JButton();
        fakex1 = new javax.swing.JButton();
        newId = new javax.swing.JTextField();
        MC_CMB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(512, 387));
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setMinimumSize(new java.awt.Dimension(512, 387));
        jPanel3.setLayout(null);

        npass.setFont(new java.awt.Font("Bookshelf Symbol 7", 0, 18)); // NOI18N
        npass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npassActionPerformed(evt);
            }
        });
        jPanel3.add(npass);
        npass.setBounds(170, 230, 200, 40);

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel3.add(back);
        back.setBounds(10, 350, 90, 30);

        next2.setText("NEXT");
        next2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next2ActionPerformed(evt);
            }
        });
        jPanel3.add(next2);
        next2.setBounds(410, 350, 90, 30);

        fakex2.setBackground(new java.awt.Color(255, 51, 51));
        fakex2.setText("X");
        fakex2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fakex2ActionPerformed(evt);
            }
        });
        jPanel3.add(fakex2);
        fakex2.setBounds(450, 6, 60, 30);

        eulacb.setBackground(new java.awt.Color(34, 34, 34));
        eulacb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eulacbActionPerformed(evt);
            }
        });
        jPanel3.add(eulacb);
        eulacb.setBounds(70, 289, 20, 21);

        eula.setText("Read EULA");
        eula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eulaActionPerformed(evt);
            }
        });
        jPanel3.add(eula);
        eula.setBounds(190, 350, 140, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Credentials.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 580, 390);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);
        jPanel2.add(nsname);
        nsname.setBounds(190, 300, 200, 30);

        preId.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        preId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preIdActionPerformed(evt);
            }
        });
        jPanel2.add(preId);
        preId.setBounds(190, 240, 30, 30);

        backlog.setText("BACK");
        backlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backlogActionPerformed(evt);
            }
        });
        jPanel2.add(backlog);
        backlog.setBounds(10, 350, 90, 30);

        next1.setText("NEXT");
        next1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next1ActionPerformed(evt);
            }
        });
        jPanel2.add(next1);
        next1.setBounds(410, 350, 90, 30);

        fakex1.setBackground(new java.awt.Color(255, 51, 51));
        fakex1.setText("X");
        fakex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fakex1ActionPerformed(evt);
            }
        });
        jPanel2.add(fakex1);
        fakex1.setBounds(450, 6, 60, 30);

        newId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newIdActionPerformed(evt);
            }
        });
        jPanel2.add(newId);
        newId.setBounds(220, 240, 170, 30);

        MC_CMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MEMBER", "COACH" }));
        MC_CMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MC_CMBActionPerformed(evt);
            }
        });
        jPanel2.add(MC_CMB);
        MC_CMB.setBounds(290, 130, 160, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Register.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 580, 390);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    public JPanel getjPanel1() {
//        return jPanel1;
//    }

    private void fakex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fakex1ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_fakex1ActionPerformed

    public boolean checkIfS()
    {
        try {
               
            Integer.parseInt(newId.getText());
                    
        } catch (NumberFormatException exception) {
            // Output expected NumberFormatException.
          
         return false;
        }
       return true;
    }

    public JTextField getNpass() {
        return npass;
    }

    public JTextField getNewId() {
        return newId;
    }

    public JTextField getNsname() {
        return nsname;
    }
    
    
    private void next1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next1ActionPerformed
        if(newId.getText().isEmpty())
            JOptionPane.showMessageDialog(jPanel2, "Enter new ID!",
                    "ID FIELD EMPTY", HEIGHT);
        else if(nsname.getText().isEmpty())
        JOptionPane.showMessageDialog(jPanel2, "Enter Name!",
                    "NAME FIELD EMPTY", HEIGHT);
        else
        {       
           if(!checkIfS())
              JOptionPane.showMessageDialog(jPanel2, "ID MUST BE 8 DIGIT INTEGERS!",
                    "ID TYPE MISSMATCH", HEIGHT);
           else
           {
               Uname = nsname.getText();
               finalId= newId.getText();
               if(String.valueOf(MC_CMB.getSelectedItem()).equalsIgnoreCase("member"))
                    finalId="1"+finalId;
               else
                   finalId="2"+finalId;
               UID =Integer.parseInt(finalId);
               this.jPanel2.setVisible(false);
               jPanel3.setVisible(true);
           }
        
           
                    
            
                    
        
            
            
        }   
        // TODO add your handling code here:
    }//GEN-LAST:event_next1ActionPerformed

    public JPanel getjPanel3() {
        return jPanel3;
    }

    private void backlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backlogActionPerformed

          this.setVisible(false);
        pf.setLocationRelativeTo(null);
        pf.setSize(512, 387);
        pf.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backlogActionPerformed

    private void preIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preIdActionPerformed

    private void newIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newIdActionPerformed

    public JTextField getPreId() {
        return preId;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    private void MC_CMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MC_CMBActionPerformed
        if(String.valueOf(this.MC_CMB.getSelectedItem())
                .equalsIgnoreCase("Member"))
            preId.setText("1");
        else
            preId.setText("2");

        // TODO add your handling code here:
    }//GEN-LAST:event_MC_CMBActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void next2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next2ActionPerformed
        if(npass.getText().isEmpty())
            JOptionPane.showMessageDialog(jPanel3, "YOU MUST CREATE A PASSWORD",
                    "PASSWORD", HEIGHT);
        else if(!eulacb.isSelected()){
            eulacb.setBackground(new java.awt.Color(255, 0, 0));
        JOptionPane.showMessageDialog(jPanel3, "YOU CAN NOT PROCEED WITHOUT AGGREEING TO OUR TERMS",
                    "EULA", HEIGHT);
        }
        else
        {
        passn = npass.getText();
        this.setVisible(false);
        if(String.valueOf(MC_CMB.getSelectedItem()).equalsIgnoreCase("member"))
        {
        cf.setVisible(true);
        cf.setSize(576, 432);
        cf.setLocationRelativeTo(null);
        }
        else
        {
        cof.setVisible(true);
        cof.setSize(576, 432);
        cof.setLocationRelativeTo(null);
        }

        
//        system.UniverseHealthSys.addPerson(UID, Uname, passn);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_next2ActionPerformed

    private void fakex2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fakex2ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_fakex2ActionPerformed

    private void eulacbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eulacbActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_eulacbActionPerformed

    public static void openWebpage(String urlString) {
    try {
        Desktop.getDesktop().browse(new URL(urlString).toURI());
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    public String getFinalId() {
        return finalId;
    }
    
    private void eulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eulaActionPerformed
        openWebpage("http://ajanovdavut.com/");
        // TODO add your handling code here:
    }//GEN-LAST:event_eulaActionPerformed

    private void npassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npassActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> MC_CMB;
    private javax.swing.JButton back;
    private javax.swing.JButton backlog;
    private javax.swing.JButton eula;
    private javax.swing.JCheckBox eulacb;
    private javax.swing.JButton fakex1;
    private javax.swing.JButton fakex2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField newId;
    private javax.swing.JButton next1;
    private javax.swing.JButton next2;
    private javax.swing.JTextField npass;
    private javax.swing.JTextField nsname;
    private javax.swing.JTextField preId;
    // End of variables declaration//GEN-END:variables

    private boolean UniverseHealthSys(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
