/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import system.UniverseHealthSys;
import static system.UniverseHealthSys.searchPerson;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author Nima's Stuff
 */
public class PostRFrame extends javax.swing.JFrame {

    
    LoginFrame lf1 = new LoginFrame(this);
    UserInfoFrame ui = new UserInfoFrame(this);
    Exit ex = new Exit();
         
    /**
     * Creates new form PostRFrame
     */
    public PostRFrame() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pass = new javax.swing.JTextField();
        Id = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        reg = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        pass.setFont(new java.awt.Font("Bookshelf Symbol 7", 0, 18)); // NOI18N
        jPanel1.add(pass);
        pass.setBounds(260, 250, 190, 40);
        jPanel1.add(Id);
        Id.setBounds(260, 180, 190, 40);

        next.setText("NEXT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next);
        next.setBounds(360, 300, 90, 30);

        reg.setText("REGISTER");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        jPanel1.add(reg);
        reg.setBounds(260, 300, 90, 30);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(433, 10, 70, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Login-final.png"))); // NOI18N
        jLabel1.setText("X");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 390);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public boolean checkIdS()
    {
        try {
               
            Integer.parseInt(Id.getText());
                    
        } catch (NumberFormatException exception) {
            // Output expected NumberFormatException.
          
         return false;
        }
       return true;
    }
    
    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        if(!checkIdS() )
              JOptionPane.showMessageDialog(jPanel1, "ID MUST BE 8 DIGIT INTEGERS!",
                    "ID TYPE MISSMATCH", HEIGHT);
        else if(!(Integer.parseInt(Id.getText())/10000000>=1) || !(Integer.parseInt(Id.getText())/100000000<1))
        JOptionPane.showMessageDialog(jPanel1, "ID MUST BE 8 DIGIT INTEGERS!",
                    "ID TYPE MISSMATCH", HEIGHT);
                else{
        if(Id.getText().isEmpty())
            JOptionPane.showMessageDialog(jPanel1, "ENTER ID!");
            
            else if(!UniverseHealthSys.checkId(Integer.parseInt(Id.getText())))
                JOptionPane.showMessageDialog(jPanel1, "You do not have an"
                        + " account!\nPlease register to the system.", "ID NOT FOUND", HEIGHT);
            else if(!searchPerson(Integer.parseInt(Id.getText()), pass.getText()))
                        JOptionPane.showMessageDialog(jPanel1, "Wrong Password!"
                                , "PASSWORD ERROR", HEIGHT);
                
            else{
                ui.setSize(666, 500);
                this.setVisible(false);
                ui.setLocationRelativeTo(null);
                ui.setVisible(true);
                ui.showInfo();
                
            }
        
                
            }

                
            
        // TODO add your handling code here:
      
        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        ex.setSize(650,650);
        ex.setLocationRelativeTo(null);
        ex.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        lf1.setLocationRelativeTo(null);
        lf1.setVisible(true);
        lf1.getjPanel2().setVisible(true);
        lf1.getjPanel3().setVisible(false);
        lf1.getPreId().setText("1");
        lf1.getPreId().setEditable(false);
        lf1.getjPanel3().setSize(512, 387);
        lf1.getjPanel2().setSize(512, 387);
        this.setVisible(false);
        lf1.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_regActionPerformed

    public boolean checkIfS()
    {
        try {
               
            Integer.parseInt(pass.getText());
                    
        } catch (NumberFormatException exception) {
            // Output expected NumberFormatException.
          
         return false;
        }
       return true;
    }
    /**
     * @param args the command line arguments
     */

    /**
     * @param args the command line arguments
     */
    public JTextField getId() {
        return Id;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton next;
    private javax.swing.JTextField pass;
    private javax.swing.JButton reg;
    // End of variables declaration//GEN-END:variables
}
