/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.io.Serializable;
import system.UniverseHealthSys;


/**
 *
 * @author Nima's Stuff
 */
public class UserInfoFrame extends javax.swing.JFrame{
PostRFrame lg;
        Exit ex = new Exit();


    public UserInfoFrame(PostRFrame lf) {
        initComponents();
        lg=lf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        infotype = new javax.swing.JComboBox<>();
        close = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(34, 34, 34));

        infotype.setBackground(new java.awt.Color(34, 34, 34));
        infotype.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        infotype.setForeground(new java.awt.Color(255, 204, 0));
        infotype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MY INFORMATION", "COACHES" }));
        infotype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infotypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(infotype, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addComponent(infotype, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(180, 20, 280, 60);

        close.setBackground(new java.awt.Color(255, 0, 0));
        close.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Close.png"))); // NOI18N
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(500, 290, 150, 150);

        logout.setBackground(new java.awt.Color(0, 153, 0));
        logout.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Logout.png"))); // NOI18N
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout);
        logout.setBounds(10, 280, 160, 160);

        info.setBackground(new java.awt.Color(34, 34, 34));
        info.setColumns(20);
        info.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        info.setForeground(new java.awt.Color(255, 255, 51));
        info.setRows(5);
        jScrollPane1.setViewportView(info);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 130, 270, 320);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/UI - 65.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 670, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
         this.setVisible(false);
        ex.setSize(650,650);
        ex.setLocationRelativeTo(null);
        ex.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        lg.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void infotypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infotypeActionPerformed
        showInfo();
            // TODO add your handling code here:
    }//GEN-LAST:event_infotypeActionPerformed

    void showInfo()
    {
        if(String.valueOf(infotype.getSelectedItem()).equalsIgnoreCase("My information"))
            info.setText(UniverseHealthSys.display(Integer.parseInt(lg.getId().getText())));
        else{
            info.setText(UniverseHealthSys.seeCoaches());
        }
//            info.setText(UniverseHealthSys.display(Integer.parseInt(lg.getId().getText())));

    }
    
    /**
     * @param args the command line arguments
  **/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JTextArea info;
    private javax.swing.JComboBox<String> infotype;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logout;
    // End of variables declaration//GEN-END:variables
}
